SELECT
    FRANCHISE_ID,
    FIRST_NAME AS ONWER_FIRST_NAME,
    LAST_NAME AS OWNER_LAST_NAME,
    CITY AS OWNER_CITY,
    COUNTRY AS OWNER_COUNTRY,
    LOWER(E_MAIL) AS EMAIL,
    PHONE_NUMBER
FROM {{ source('pos', 'franchise') }}